### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Poggen** [peterasplund/MagentoReact#1]
# Components
- [x] Product (@peterasplund)
  - [ ] Configurable
  - [ ] Bundle
  - [x] Virtual
- [x] Product subcomponents
  - [x] Name
  - [ ] Brand
  - [x] ShortDescription
  - [x] Description
  - [x] Image
  - [x] ImageGallery
  - [x] Price
  - [x] MSRP
  - [x] RelatedProducts
- [x] ProductList
- [ ] Customer
  - [ ] Balance (for points / internal credit)
  - [ ] Adress
- [ ] Checkout
  - [ ] GrandTotals
    - [ ] Tax
    - [ ] Shipping
    - [ ] Discount
  - [ ] Coupon
  - [ ] Newsletter
  - [ ] Success
  - [ ] Terms & Conditions
- [x] CMS-page
- [ ] staticBlock
- [ ] contentSlider
- [ ] Login
- [ ] Search
- [ ] ProductFilter
  - [ ] By price
  - [ ] By attribute
# ToDo
- [x] Dockerize a standard magento installation (https://hub.docker.com/r/paimpozhil/magento-docker/) and add it to this repo.
- [x] Styling system incl. basic styling
- [x] ~~Gulp~~ _Webpack_ for asset mgmt
- [ ] Implement `fetch` or some other promise polyfill
- [ ] Support for payment methods
- [ ] Support for translations
- [ ] Analytics implementation (https://github.com/yahoo/react-i13n)
- [ ] GraphQL & Apollo (https://github.com/apollostack/apollo)

**Comment by peterasplund** [comment]
Satt hela kvällen igår och läste om olika mer avancerade use cases för Webpack. Jag tror definitivt att vi klarar oss utan Gulp. Om vi behöver lägga till Gulp senare så går det ganska lätt.
